version: '3.8'

services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: foodbox
      DB_PASSWORD: 111
      DB_DATABASE: foodbox
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
  db:
    image: postgis/postgis:14-3.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 111
      POSTGRES_USER: foodbox
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
